const express = require('express');
const multer = require('multer');
const cors = require('cors');
const path = require('path');
const { Resend } = require('resend');

const app = express();
const PORT = 3000;

// Resend setup
const resend = new Resend(process.env.RESEND_API_KEY || 're_7BgaB9pJ_P6LNyvivC5D5t9SznjCy4r7F');

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Multer for file uploads (store in memory for email attachment)
const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB max
  fileFilter: (req, file, cb) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf'];
    if (allowed.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('Only images and PDF files are allowed'), false);
    }
  }
});

// Build admin email HTML
function buildAdminEmailHTML(data) {
  const fieldRows = [
    ['Full Name', data.fullName],
    ['Email', data.email],
    ['Phone', data.phone],
    ['Gender', data.gender],
    ['City / Location', data.city],
    ['Date of Birth', data.dob],
    ['Professional Status', data.professionalStatus],
    ['Years of Experience', data.experience],
    ['Previous Companies', data.previousCompanies || 'N/A (Fresher)'],
    ['Key Skills', data.skills],
    ['LinkedIn', data.linkedin || 'Not provided'],
    ['Why Idyll Productions?', data.whyJoin],
    ['Value to Team', data.valueToTeam || 'Not provided'],
    ['Availability', data.availability],
    ['Work Mode', data.workMode],
  ];

  const rows = fieldRows.map(([label, value]) => `
    <tr>
      <td style="padding: 12px 16px; font-weight: 600; color: #0A0A0F; background: #FAF9F6; border-bottom: 1px solid #f0ece6; width: 200px; vertical-align: top; font-size: 14px;">${label}</td>
      <td style="padding: 12px 16px; color: #333; border-bottom: 1px solid #f0ece6; font-size: 14px; line-height: 1.6;">${value || '—'}</td>
    </tr>
  `).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head><meta charset="UTF-8"></head>
  <body style="margin: 0; padding: 0; background: #f4f1ec; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;">
    <div style="max-width: 640px; margin: 0 auto; padding: 40px 20px;">
      <!-- Header -->
      <div style="text-align: center; padding: 32px 0 24px;">
        <img src="https://res.cloudinary.com/dxd79mrse/image/upload/v1781437518/Idyll_Productions_Black_aburqi.png" alt="Idyll Productions" style="height: 40px;" />
      </div>
      
      <!-- Main Card -->
      <div style="background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 2px 16px rgba(0,0,0,0.06);">
        <!-- Orange Banner -->
        <div style="background: linear-gradient(135deg, #FF7A3A, #FF6B35, #FFB86A); padding: 28px 32px;">
          <h1 style="margin: 0; color: #fff; font-size: 22px; font-weight: 700;">New Sales Executive Application</h1>
          <p style="margin: 8px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">Received on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
        </div>
        
        <!-- Table -->
        <table style="width: 100%; border-collapse: collapse;">
          ${rows}
        </table>

        ${data.hasAttachment ? `
        <div style="padding: 16px 16px 20px; background: #FAF9F6; border-top: 1px solid #f0ece6;">
          <p style="margin: 0; font-size: 13px; color: #666;">📎 Photo/Resume attached to this email</p>
        </div>` : ''}
      </div>

      <!-- Footer -->
      <div style="text-align: center; padding: 24px 0 0;">
        <p style="margin: 0; font-size: 11px; color: #999;">This email was generated by the Idyll Productions Hiring System</p>
        <p style="margin: 4px 0 0; font-size: 11px; color: #999;">© 2026 Idyll Productions. All rights reserved.</p>
      </div>
    </div>
  </body>
  </html>`;
}

// Build applicant confirmation email HTML
function buildConfirmationEmailHTML(name) {
  return `
  <!DOCTYPE html>
  <html>
  <head><meta charset="UTF-8"></head>
  <body style="margin: 0; padding: 0; background: #f4f1ec; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;">
    <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
      <!-- Header -->
      <div style="text-align: center; padding: 32px 0;">
        <img src="https://res.cloudinary.com/dxd79mrse/image/upload/v1781445552/idyll-productions-orange_q6o4ap.png" alt="Idyll Productions" style="height: 44px;" />
      </div>
      
      <!-- Main Card -->
      <div style="background: #ffffff; border-radius: 16px; padding: 40px 36px; box-shadow: 0 2px 16px rgba(0,0,0,0.06);">
        <!-- Orange accent line -->
        <div style="width: 48px; height: 4px; background: linear-gradient(90deg, #FF6B35, #FFB86A); border-radius: 2px; margin-bottom: 28px;"></div>
        
        <h1 style="margin: 0 0 24px; font-size: 24px; font-weight: 700; color: #0A0A0F;">Application Received</h1>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">Hello <strong>${name}</strong>,</p>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">Thank you for applying to join <strong>Idyll Productions</strong>.</p>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">We have successfully received your application and our team will review the information provided. If we believe your profile is a good fit for our current requirements, we will contact you for the next steps.</p>
        
        <p style="margin: 0 0 28px; font-size: 15px; line-height: 1.7; color: #333;">We appreciate your interest in becoming a part of Idyll Productions and wish you the very best.</p>
        
        <div style="border-top: 1px solid #f0ece6; padding-top: 24px;">
          <p style="margin: 0; font-size: 15px; color: #333;">Regards,</p>
          <p style="margin: 4px 0 0; font-size: 15px; font-weight: 700; color: #0A0A0F;">Idyll Productions Team</p>
        </div>
      </div>

      <!-- Footer -->
      <div style="text-align: center; padding: 28px 0 0;">
        <div style="width: 100%; height: 3px; background: linear-gradient(90deg, #FF6B35, #FFB86A, #FF6B35); border-radius: 2px; margin-bottom: 20px;"></div>
        <p style="margin: 0; font-size: 11px; color: #999;">© 2026 Idyll Productions. All rights reserved.</p>
        <p style="margin: 4px 0 0; font-size: 11px; color: #bbb;">This is an automated confirmation email. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>`;
}

// API: Submit application
app.post(['/api/submit', '/submit'], upload.single('photo'), async (req, res) => {
  try {
    const data = req.body;
    const file = req.file;

    // Validate required fields
    if (!data.fullName || !data.email || !data.phone || !data.gender) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    data.hasAttachment = !!file;

    // Build attachment array
    const attachments = [];
    if (file) {
      attachments.push({
        filename: file.originalname,
        content: file.buffer,
      });
    }

    // 1. Send admin notification email
    const adminEmail = await resend.emails.send({
      from: 'Idyll Productions Hiring <hiring@idyllproductions.work>',
      to: ['harshidyllproductions@gmail.com'],
      subject: `New Sales Executive Application — ${data.fullName}`,
      html: buildAdminEmailHTML(data),
      attachments,
    });

    console.log('Admin email sent:', adminEmail);

    // 2. Send confirmation email to applicant
    const confirmEmail = await resend.emails.send({
      from: 'Idyll Productions <hiring@idyllproductions.work>',
      to: [data.email],
      subject: 'Application Received – Idyll Productions',
      html: buildConfirmationEmailHTML(data.fullName),
    });

    console.log('Confirmation email sent:', confirmEmail);

    res.json({ 
      success: true, 
      message: 'Application submitted successfully',
      adminEmailId: adminEmail.data?.id,
      confirmEmailId: confirmEmail.data?.id,
    });

  } catch (error) {
    console.error('Submission error:', error);
    res.status(500).json({ 
      error: 'Failed to submit application. Please try again.',
      details: error.message 
    });
  }
});

// Serve the main page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`\n🚀 Idyll Productions Hiring Form running at http://localhost:${PORT}\n`);
  });
}

module.exports = app;
